sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t nutt88/docker-test -f Dockerfile.dev .


#before_install:
  - docker build -t nutt88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nutt88/react-test npm test -- --coverage

#after_success:
  - docker build -t nutt88/multi-client ./client
  - docker build -t nutt88/multi-nginx ./nginx
  - docker build -t nutt88/multi-server ./server
  - docker build -t nutt88/multi-worker ./worker

  #Log in to the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take those images and push them to docker hub

  - docker push nutt88/multi-client
  - docker push nutt88/multi-nginx
  - docker push nutt88/multi-server
  - docker push nutt88/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-671841532854'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY