language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nutt88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nutt88/react-test npm test -- --coverage

after_success:
  - docker build -t nutt88/multi-client ./client
  - docker built -t nutt88/multi-nginx ./nginx  
  - docker built -t nutt88/multi-server ./server  
  - docker built -t nutt88/multi-worker ./worker  

  #Log in to the docker cli
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take those images and push them to docker hub

  - docker push nutt88/multi-client
  - docker push nutt88/multi-nginx
  - docker push nutt88/multi-server
  - docker push nutt88/multi-worker