language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t nutt88/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nutt88/react-test npm test -- --coverage

after_success:
  - docker build -t nutt88/multi-client ./client
  - docker built -t nutt88/multi-nginx ./nginx  
  - docker built -t nutt88/multi-server ./server  
  - docker built -t nutt88/multi-worker ./worker  